// labjs-r3.js - http://github.com/labatrockwell/LAB_JS_Framework
var LAB=LAB||{};LAB.global=this;LAB.version="r2";var included={};LAB.inherit=function(a){function b(){}if(null!=a){if(Object.create)return Object.create(a);var c=typeof a;if("object"!==c&&"function"!==c)throw TypeError();b.prototype=a;return new b}};LAB.writeScriptTag_=function(a){LAB.global.document.write('<script type="text/javascript" src="'+a+'"><\/script>');return included[a]=!0};LAB.require=function(a){a in included?console.log("already included"):LAB.writeScriptTag_(a)};
LAB.getScriptPath=function(a){for(var b=document.getElementsByTagName("script"),c=b.length-1;0<=c;--c){var d=b[c].src,e=d.length,g=a.length;if(d.substr(e-g)==a)return d.substr(0,e-g)}return""};LAB.toScriptPath=function(a){return LAB.src+a+".js"};LAB.src=LAB.getScriptPath("LabBase.js");LAB.SHIFT=16;LAB.CONTROL=17;LAB.ALT=18;LAB.COMMAND=91;LAB=LAB||{};LAB.random=function(a,b){return Math.random()*(b-a)+a};LAB.randomInt=function(a,b){return Math.floor(LAB.random(a,b))};
LAB.randomObject=function(a){return a[Math.min(LAB.randomInt(0,a.length),a.length-1)]};LAB.map=function(a,b,c,d,e){return d+(a-b)/(c-b)*(e-d)};LAB.clamp=function(a,b,c){return Math.min(Math.max(a,b),c)};LAB.degToRad=function(a){return 0.0174532925*a};LAB.radToDeg=function(a){return 57.2957795*a};Number.prototype.sign=function(){return 0<this?1:0>this?-1:0};LAB.log=function(a){window.console&&window.console.log?window.console.log(a):window.dump&&window.dump(a)};
if(!window.requestAnimationFrame)window.requestAnimationFrame=function(){return window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){window.setTimeout(a,1E3/60)}}();LAB.getQueryString=function(a){a=a.replace(/[\[]/,"\\[").replace(/[\]]/,"\\]");a=RegExp("[\\?&]"+a+"=([^&#]*)").exec(window.location.href);return null==a?"":a[1]};LAB.alphabet=LAB.alphabet||"#,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z".split(",");
if(!Function.prototype.bind)Function.prototype.bind=function(a){if("function"!==typeof this)throw new TypeError("Function.prototype.bind - what is trying to be bound is not callable");var b=Array.prototype.slice.call(arguments,1),c=this,d=function(){},e=function(){return c.apply(this instanceof d?this:a||window,b.concat(Array.prototype.slice.call(arguments)))};d.prototype=this.prototype;e.prototype=new d;return e};
window.namespace=function(a){var a=a.split("."),b=window,c;for(c=0;c<a.length;c+=1)"undefined"===typeof b[a[c]]&&(b[a[c]]={}),b=b[a[c]];return b};LAB.EventDispatcher=function(a){var b=a||null;this.getTarget=function(){return b};this.events=[]};
LAB.EventDispatcher.prototype={constructor:LAB.EventDispatcher,addEventListener:function(a,b){this.events[a]=this.events[a]||[];this.events[a]&&this.events[a].push(b)},removeEventListener:function(a,b){if(this.events[a])for(var c=this.events[a],d=c.length-1;0<=d;--d)if(c[d]===b)return c.splice(d,1),!0;return!1},hasEventListener:function(a){return this.events[a]?!0:!1},dispatchEvent:function(a,b){if("string"===typeof a)var c=new LAB.Event(a);else if("object"===typeof a)c=a;else throw"First parameter of dispatchEvent must be of type object or string";
c.target=this.getTarget();for(var d in b)c[d.toString()]=b[d];if(this.events[c.type]){d=this.events[c.type];for(var e=d.length;e--;)d[e](c);return!0}return!1}};LAB.Event=function(a){this.type=a;this.target=null};LAB.Event.CONNECTED="connected";LAB.Event.CHANGE="change";LAB.Event.COMPLETE="complete";
LAB.TouchGestureHandler=function(){function a(c){window.addEventListener("mouseup",d);f.addEventListener("mousemove",b);f.removeEventListener("mousedown",a);i=c.clientX;j=c.clientY;g(LAB.TouchEvent.PRESS);x=(new Date).getTime();h=new LAB.geom.Point(c.clientX,c.clientY)}function b(a){i=a.clientX;j=a.clientY;var b=new Date,a=b.getTime(),c=new LAB.geom.Point(i,j),d=e(c,h),f=m(c.x-h.x,h.y-c.y);d>D&&(l||(b=new Date,y=b.getTime(),n=new LAB.geom.Point(i,j)),l=!0);d>E&&(k=d,z=f,b=0<k&&0<a-t?k/(a-t):-1,-1<
b&&o.push(b),p=!0);p&&g(LAB.TouchEvent.DRAG);h=new LAB.geom.Point(c.x,c.y);t=a}function c(a){a.target==f&&(f.removeEventListener("mouseout",c),g(LAB.TouchEvent.OUT))}function d(c){i=c.clientX;j=c.clientY;f.addEventListener("mousedown",a);f.removeEventListener("mousemove",b);window.removeEventListener("mouseup",d);u=(new Date).getTime();var c=u-x,C=u-y;c<=F&&!p&&!l&&g(LAB.TouchEvent.TAP);for(var s=0,h=0,k=o.length;h<k;h++)s+=o[h];v=s/o.length;C<=w&&l&&(q=new LAB.geom.Point(i,j),A=m(q.x-n.x,n.y-q.y),
r=e(q,n),B=0<r&&0<c?r/c:-1,g(LAB.TouchEvent.FLICK));g(LAB.TouchEvent.RELEASE);l=p=!1;v=[]}function e(a,b){return Math.sqrt(Math.pow(b.x-a.x,2)+Math.pow(b.y-a.y,2))}function g(a){G.dispatchEvent(new LAB.TouchEvent(a))}function m(a,b){var c=Math.atan2(b,a);0>c&&(c+=6.283185);return 57.29578*c}LAB.EventDispatcher.call(this,this);var w=250,F=80,D=20,E=5,G=this,f=null,p=!1,l=!1,h,A,r,n,q,B,y,x,u,t=-1,v=[],o=[],z,k,i,j;this.register=function(b){f=b;f.addEventListener("mousedown",a)};this.unregister=function(){null!==
f&&(f.removeEventListener("mousedown",a),f.removeEventListener("mouseout",c),f.removeEventListener("mousemove",b),window.removeEventListener("mouseup",d))};this.getDragDirection=function(){return z};this.getDragDistance=function(){return k};this.getFlickDirection=function(){return A};this.getFlickDistance=function(){return r};this.getTouchX=function(){return i};this.getTouchY=function(){return j};this.getAverageVelocity=function(){return v};this.getFlickVelocity=function(){return B}};
LAB.TouchGestureHandler.prototype=LAB.inherit(LAB.EventDispatcher.prototype);LAB.TouchGestureHandler.prototype.constructor=LAB.TouchGestureHandler;LAB.TouchEvent=function(a){LAB.Event.call(this,a)};LAB.TouchEvent.TAP="touchtap";LAB.TouchEvent.FLICK="touchflick";LAB.TouchEvent.DRAG="touchdrag";LAB.TouchEvent.RELEASE="touchrelease";LAB.TouchEvent.OUT="touchout";LAB.TouchEvent.PRESS="touchPress";LAB.TouchEvent.prototype=LAB.inherit(LAB.Event.prototype);LAB.TouchEvent.prototype.constructor=LAB.TouchEvent;
LAB.agents=LAB.agents||{};LAB.agents.Agent=function(){};LAB.agents.Agent.prototype.setup=function(a,b,c,d,e,g,m,w){this.pos=[];this.myID=a||0;this.rotation=e||0;this.currentWidth=g||0;this.currentHeight=m||0;this.isVisible=w||!0;this.yScale=this.xScale=1;this.pos.x=b||0;this.pos.y=c||0;this.pos.z=d||0;this.Behaviors=[]};LAB.agents.Agent.prototype.addBehavior=function(a){this.Behaviors.push(a);a.setup(this);console.log(this.Behaviors)};LAB.agents.Agent.prototype.removeBehavior=function(){};
LAB.agents.Agent.prototype.applyBehaviors=function(){for(var a=0,a=0;a<this.Behaviors.length;a++)this.Behaviors[a].apply(this)};LAB.agents.Agent.prototype.checkIt=function(){console.log("check!")};LAB.agents=LAB.agents||{};LAB.agents.Behavior=function(){};LAB.agents.Behavior.prototype.checkIt=function(){console.log("behaving")};LAB.agents=LAB.agents||{};LAB.agents.Group=function(){this.Agents=[]};LAB.agents.Group.prototype.addToGroup=function(a){console.log(this.Agents);this.Agents.push(a)};
LAB.agents.Group.prototype.update=function(){for(var a=0,a=0;a<this.Agents.length;a++)this.Agents[a].update(),this.Agents[a].applyBehaviors()};LAB.agents.Group.prototype.draw=function(){for(var a=0,a=0;a<this.Agents.length;a++)this.Agents[a].draw()};var thing=$.extend(!0,LAB.agents.Group.prototype,LAB.agents.Agent.prototype);LAB.app=LAB.app||{};
LAB.app.BaseApp=function(){LAB.EventDispatcher.call(this,this);this.mouse={x:0,y:0,bDown:!1};this.windowEventsRegistered=this.keyEventsRegistered=this.mouseEventsRegistered=!1;this.startTime=Date.now();this.elapsedTime=0};LAB.app.BaseApp.prototype=new LAB.EventDispatcher;LAB.app.BaseApp.prototype.constructor=LAB.app.BaseApp;LAB.app.BaseApp.prototype.supr=LAB.EventDispatcher.prototype;
LAB.app.BaseApp.prototype.begin=function(){this.registerWindowEvents();this.registerKeyEvents();this.registerMouseEvents();this.setup();this.animate()};LAB.app.BaseApp.prototype.setup=function(){};LAB.app.BaseApp.prototype.preupdate=function(){};LAB.app.BaseApp.prototype.update=function(){};LAB.app.BaseApp.prototype.predraw=function(){};LAB.app.BaseApp.prototype.draw=function(){};LAB.app.BaseApp.prototype.postdraw=function(){};
LAB.app.BaseApp.prototype.animate=function(a){if(void 0!==a)this.elapsedTime=a-this.startTime;requestAnimationFrame(this.animate.bind(this),this);this.preupdate();this.update();this.predraw();this.draw();this.postdraw()};
LAB.app.BaseApp.prototype.registerWindowEvents=function(){if(!this.windowEventsRegistered)window.addEventListener("focus",this._onWindowFocus.bind(this)),window.addEventListener("blur",this._onWindowBlur.bind(this)),window.addEventListener("resize",this._onWindowResized.bind(this)),this.windowEventsRegistered=!0};
LAB.app.BaseApp.prototype.unregisterWindowEvents=function(){if(this.windowEventsRegistered)window.removeEventListener("focus",this._onWindowFocus.bind(this)),window.removeEventListener("blur",this._onWindowBlur.bind(this)),window.removeEventListener("resize",this._onWindowResized.bind(this)),this.windowEventsRegistered=!1};LAB.app.BaseApp.prototype._onWindowResized=function(){this.onWindowResized(window.innerWidth,window.innerHeight)};LAB.app.BaseApp.prototype.onWindowResized=function(){};
LAB.app.BaseApp.prototype._onWindowFocus=function(){this.onWindowFocus()};LAB.app.BaseApp.prototype.onWindowFocus=function(){};LAB.app.BaseApp.prototype._onWindowBlur=function(){this.onWindowBlur()};LAB.app.BaseApp.prototype.onWindowBlur=function(){};
LAB.app.BaseApp.prototype.registerMouseEvents=function(){if(!this.mouseEventsRegistered)window.addEventListener("mousemove",this._onMouseMoved.bind(this)),window.addEventListener("mousedown",this._onMousePressed.bind(this)),window.addEventListener("mouseup",this._onMouseReleased.bind(this)),this.mouseEventsRegistered=!0};
LAB.app.BaseApp.prototype.unregisterMouseEvents=function(){if(this.mouseEventsRegistered)window.removeEventListener("mousemove",this._onMouseMoved.bind(this)),window.removeEventListener("mousedown",this._onMousePressed.bind(this)),window.removeEventListener("mouseup",this._onMouseReleased.bind(this)),this.mouseEventsRegistered=!1};LAB.app.BaseApp.prototype.onMouseMoved=function(){};LAB.app.BaseApp.prototype.onMousePressed=function(){};LAB.app.BaseApp.prototype.onMouseDragged=function(){};
LAB.app.BaseApp.prototype.onMouseReleased=function(){};LAB.app.BaseApp.prototype._onMouseMoved=function(a){this.mouse.bDown?this._onMouseDragged(a):(this.mouse.x=a.clientX,this.mouse.y=a.clientY,this.dispatchEvent("onMouseMoved",this.mouse),this.onMouseMoved(this.mouse.x,this.mouse.y))};LAB.app.BaseApp.prototype._onMousePressed=function(a){this.mouse.x=a.clientX;this.mouse.y=a.clientY;this.mouse.bDown=!0;this.dispatchEvent("onMousePressed",this.mouse);this.onMousePressed(this.mouse.x,this.mouse.y)};
LAB.app.BaseApp.prototype._onMouseReleased=function(a){this.mouse.x=a.clientX;this.mouse.y=a.clientY;this.mouse.bDown=!1;this.dispatchEvent("onMouseReleased",this.mouse);this.onMouseReleased(this.mouse.x,this.mouse.y)};LAB.app.BaseApp.prototype._onMouseDragged=function(a){this.mouse.x=a.clientX;this.mouse.y=a.clientY;this.dispatchEvent("onMouseDragged",this.mouse);this.onMouseDragged(this.mouse.x,this.mouse.y)};
LAB.app.BaseApp.prototype.registerKeyEvents=function(){if(!this.keyEventsRegistered)window.addEventListener("keydown",this._onDocumentKeyDown.bind(this)),window.addEventListener("keyup",this._onDocumentKeyUp.bind(this)),this.keyEventsRegistered=!0};
LAB.app.BaseApp.prototype.unregisterKeyEvents=function(){if(this.keyEventsRegistered)window.removeEventListener("keydown",this._onDocumentKeyDown.bind(this)),window.removeEventListener("keyup",this._onDocumentKeyUp.bind(this)),this.keyEventsRegistered=!1};LAB.app.BaseApp.prototype.onDocumentKeyDown=function(){};LAB.app.BaseApp.prototype._onDocumentKeyDown=function(a){this.dispatchEvent("onDocumentKeyDown",a);this.onDocumentKeyDown(a.keyCode)};LAB.app.BaseApp.prototype.onDocumentKeyUp=function(){};
LAB.app.BaseApp.prototype._onDocumentKeyUp=function(a){this.dispatchEvent("onDocumentKeyUp",a);this.onDocumentKeyUp(a.keyCode)};LAB.getElapsedTimeMillis=LAB.app.BaseApp.prototype.getElapsedTimeMillis=function(){return this.elapsedTime};LAB.getElapsedTimeSeconds=LAB.app.BaseApp.prototype.getElapsedTimeSeconds=function(){return this.elapsedTime/1E3};LAB.geom=LAB.geom||{};LAB.geom.Point=function(a,b,c){this.x=a||0;this.y=b||0;this.z=c||0};LAB.geom=LAB.geom||{};
LAB.geom.Rect=function(a,b,c,d,e){this.x=a||0;this.y=b||0;this.z=c||0;this.width=d||0;this.height=e||0};LAB.sound=LAB.sound||{};if("function"==typeof webkitAudioContext)LAB.sound.Context=LAB.sound.Context||new webkitAudioContext;LAB.sound=LAB.sound||{};
LAB.sound.Player=function(a,b,c,d){LAB.EventDispatcher.call(this,this);this.loop=b||!1;this.autoplay=c||!1;this.controls=d||!1;this.eventsRegistered=!1;a?(this.playerElement=document.createElement("audio"),this.playerElement.style.border="0px none",this.loop&&this.playerElement.setAttribute("loop","loop"),this.autoplay&&this.playerElement.setAttribute("autoplay","autoplay"),this.controls&&this.playerElement.setAttribute("controls","controls"),a.appendChild(this.playerElement),this.playerElement.parent=
a):console.log("ERROR! please pass in an HTML element to attach the player to")};LAB.sound.Player.prototype=new LAB.EventDispatcher;LAB.sound.Player.prototype.constructor=LAB.sound.Player;LAB.sound.Player.prototype.supr=LAB.EventDispatcher.prototype;LAB.sound.Player.prototype.loadFile=function(a){this.registerEvents();this.playerElement.setAttribute("src",a);this.playerElement.load()};LAB.sound.Player.prototype.play=function(){this.playerElement.play()};LAB.sound.Player.prototype.pause=function(){this.playerElement.pause()};
LAB.sound.Player.prototype.setVolume=function(a){this.playerElement.volume=a};LAB.sound.Player.prototype.seekTo=function(a){this.playerElement.currentTime=a};LAB.sound.Player.prototype.registerEvents=function(){if(!this.eventsRegistered)this.playerElement.addEventListener("load",this.onLoad),this.playerElement.addEventListener("ended",this.onEnded),this.playerElement.addEventListener("error",this.onError),this.eventsRegistered=!0};
LAB.sound.Player.prototype.onLoad=function(a){this.dispatchEvent("onLoad",a)};LAB.sound.Player.prototype.onEnded=function(a){this.dispatchEvent("onEnded",a)};LAB.sound.Player.prototype.onError=function(a){console.log(a);this.dispatchEvent("onError",a)};LAB.sound.Player.prototype.getElement=function(){return this.playerElement};LAB.sound.Player.prototype.isLooping=function(){return this.loop};LAB.sound.Player.prototype.isAutoplay=function(){return this.autoplay};
LAB.sound.Player.prototype.hasControls=function(){return this.controls};LAB.sound.Player.prototype.setLooping=function(a){(this.loop=a)?this.playerElement.setAttribute("loop","loop"):this.playerElement.removeAttribute("loop")};LAB.sound.Player.prototype.setAutoplay=function(a){(this.autoplay=a)?this.playerElement.setAttribute("autoplay","autoplay"):this.playerElement.removeAttribute("autoplay")};
LAB.sound.Player.prototype.setControls=function(a){(this.controls=a)?this.playerElement.setAttribute("controls","controls"):this.playerElement.removeAttribute("controls")};LAB.sound=LAB.sound||{};LAB.sound.WAPlayer=function(){LAB.EventDispatcher.call(this,this);this.buffer=null;this.pan=new LAB.geom.Point;this.gain=this.pitch=0;this.currentSource=this.filter=null;this.currentTime=0;this.panner=LAB.sound.Context.createPanner();this.panner.setPosition(0,0,0);this.end=this.start=0};
LAB.sound.WAPlayer.prototype.loadFile=function(a){var b=new XMLHttpRequest;b.parent=this;b.open("GET",a,!1);b.responseType="arraybuffer";b.parent=this;b.onload=function(){b.parent.buffer=LAB.sound.Context.createBuffer(b.response,!0);b.parent.end=Math.floor(b.parent.buffer.duration)};b.send()};LAB.sound.WAPlayer.prototype.setFilter=function(a){this.filter=a};
LAB.sound.WAPlayer.prototype.play=function(){var a=LAB.sound.Context.createBufferSource();a.playbackRate.value=this.pitch;a.gain=this.gain;a.buffer=this.buffer;null!=this.filter?(a.connect(this.filter),this.filter.connect(this.panner)):a.connect(this.panner);this.panner.connect(LAB.sound.Context.destination);a.noteGrainOn(0,this.start,this.end)};LAB.sound.WAPlayer.prototype.setGain=function(a){this.gain=a};
LAB.sound.WAPlayer.prototype.setPan=function(a,b,c){this.pan.x=a;this.pan.y=b||this.pan.y;this.pan.z=c||this.pan.z;this.panner.setPosition(this.pan.x,this.pan.y,this.pan.z)};LAB.sound.WAPlayer.prototype.setPitch=function(a){this.pitch=Math.pow(2,a/1200)};LAB=LAB||{};LAB.utils=LAB.utils||{};
LAB.utils.DOMElement=function(a,b){if(a)if(b)"string"==typeof b?(this.parent=document.getElementById(b),null!=this.parent?this.element=this.parent.querySelector("#"+a):console.warn("parent is null!")):(this.parent=b,this.element=this.parent.element.querySelector("#"+a));else if(this.element=document.getElementById(a),null==this.element)this.element=document.createElement("div"),console.warn("invalid id, this.element = div")};
LAB.utils.DOMElement.prototype={set x(a){this.element.style.left=a+"px"},set y(a){this.element.style.top=a+"px"},set left(a){this.y=a},set top(a){this.y=a},set right(a){this.element.style.right=a+"px"},set bottom(a){this.element.style.bottom=a+"px"},set opacity(a){this.element.style.opacity=a},set html(a){this.element.innerHTML=a},get x(){return this.element.clientTop},get y(){return this.element.clientLeft},get left(){return this.element.clientLeft},get top(){return this.element.clientTop},get right(){return this.element.clientRight},
get bottom(){return this.element.clientBottom},get opacity(){return this.element.style.opacity},get hidden(){return"hidden"==this.element.style.visibility}};LAB.utils.DOMElement.prototype.hide=function(){this.element.style.visibility="hidden"};LAB.utils.DOMElement.prototype.show=function(){this.element.style.visibility="visible"};LAB.utils.DOMElement.prototype.update=function(){"0"==this.opacity&&!this.hidden&&this.hide()};
LAB.utils.DOMElement.prototype.clone=function(a){return this.element.cloneNode(a||!0)};LAB.utils=LAB.utils||{};LAB.utils.WebSocket=function(a,b){this.host=a||"ws://localhost:8888";if(b)this.protocol=b};LAB.utils.WebSocket.prototype.connect=function(){try{this.socket=this.protocol?new WebSocket(this.host,this.protocol):new WebSocket(this.host),this.socket._parent=this,this.socket.onmessage=this._onMessageReceived,this.socket.onopen=this._onConnectionOpened,this.socket.onclose=this._onConnectionClosed}catch(a){console.log(a)}};
LAB.utils.WebSocket.prototype.sendData=function(a){console.log("sending: "+a);this.socket.send(a)};LAB.utils.WebSocket.prototype._onConnectionOpened=function(){this._parent.onConnectionOpened()};LAB.utils.WebSocket.prototype.onConnectionOpened=function(){};LAB.utils.WebSocket.prototype._onConnectionClosed=function(){this._parent.onConnectionClosed()};LAB.utils.WebSocket.prototype.onConnectionClosed=function(){};LAB.utils.WebSocket.prototype._onMessageReceived=function(a){var b=a.data;try{b=jQuery.parseJSON(a.data)}catch(c){}this._parent.onMessageReceived(b)};
LAB.utils.WebSocket.prototype.onMessageReceived=function(a){console.log(a)};
